name: issue-automation
on:
  issues:
    types: [opened]
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "clone"
      - name: cloning
        uses: dpanayotov/issue-cloner@v0.2
        with:
          label: "clone"
          targetRepo: anboralabs/yopay-initializer-rappi
          token: ${{ secrets.CLONE_ISSUE_TOKEN }}